import { CATALOG, defaultJob } from '../catalog';
import { defaultJob as defaultV1 } from '../versions/v1/catalog';
import { estimateJob as estimateV1 } from '../versions/v1/pricing';
import { estimateJob } from '../pricing';
import { composeCatalogProposal, normalizeCatalogProposal, catalogAnalytics } from '../proposal';
import { catalogDocumentText } from '../document';
import { jobSchema } from '../schema';
const client = { client_name: 'Customer', client_email: 'test@example.com', contact_phone: '555-0100', service_location: 'Test home', facility_size: 1500, service_frequency: 'one-time' };
it.each(CATALOG.map(s => s.id))('prices %s on first load without access or customer details', id => {
  expect(estimateJob(defaultJob(id)).selectedPrice).toBeGreaterThan(0);
});
it.each(CATALOG.map(s => s.id))('customer copy and privacy snapshot: %s', id => {
  const p = composeCatalogProposal({ job: { ...defaultJob(id), access: 'lockbox 4821; alarm 998877; gate 9321' }, client });
  const text = catalogDocumentText(p.generated_content!);
  expect(text).not.toMatch(/4821|998877|9321|operator|suggested|Veltex|2\.167|\.\./i);
  expect(text).toContain('Your price:');
  expect(text).toMatchSnapshot();
});
it.each(['Keystone Cleaning', 'Pinnacle Maids', 'Gateway', 'Door to Door Cleaning', 'Turnkey', 'sweeping and mopping', 'wiping interior doors', 'outdoor accessible keypad keys'])('ordinary wording never blocks pricing: %s', text => {
  const job = { ...defaultJob(), companyName: text, operatorNotes: text, scheduling: text, scopeAdditions: text, coverLetter: text };
  expect(jobSchema.safeParse(job).success).toBe(true);
  expect(estimateJob(job)).toEqual(estimateJob(defaultJob()));
});
it('supports next-day and equal-clock turnover, vacant default and per-turn terms', () => {
  const job = defaultJob('airbnb_turnover');
  expect(job.occupancy).toBe('vacant');
  job.turnover = { ...job.turnover!, nextDay: true, checkin: '11:00' };
  const p = composeCatalogProposal({ job, client });
  expect(p.generated_content).toContain('next day');
  expect(p.generated_content).toContain('per turn');
  expect(p.generated_content).not.toMatch(/one-time/i);
  expect(p.generated_content).toContain('linen par: 2');
  job.turnover.nextDay = false;
  expect(jobSchema.safeParse(job).success).toBe(false);
});
it('bedrooms and bathrooms materially change a fixed-area quote', () => {
  const job = { ...defaultJob('standard'), bedrooms: 1, bathrooms: 1 };
  const base = estimateJob(job);
  expect(estimateJob({ ...job, bathrooms: 2 }).selectedPrice - base.selectedPrice).toBeGreaterThanOrEqual(20);
  expect(estimateJob({ ...job, bedrooms: 3 }).base.laborHours).toBeGreaterThan(base.base.laborHours);
});
it('rounds up to the chosen increment and headlines per-visit recurring price', () => {
  const job = defaultJob(); job.costs.roundingIncrement = 10;
  const p = composeCatalogProposal({ job, client });
  const e = estimateJob(job);
  expect(e.selectedPrice % 10).toBe(0);
  expect(p.pricing_data?.price_range?.high).toBe(e.selectedPrice);
  expect(p.generated_content).toContain('48 hours');
  expect(p.generated_content).not.toContain('No automatic renewal');
});
it('v1 pricing stays frozen after v2 registration; status-only edits preserve historical bytes', () => {
  const job = defaultV1('standard');
  expect(estimateJob(job)).toEqual(estimateV1(job));
  const original = composeCatalogProposal({ job, client });
  // Represents a persisted proposal generated by a different historical implementation.
  original.generated_content = 'Historical accepted text';
  original.pricing_data = { price_range: { low: 173.21, high: 173.21 } };
  const changed = normalizeCatalogProposal({ ...original, status: 'sent', generated_content: 'forged' }, original);
  expect(changed.generated_content).toBe('Historical accepted text');
  expect(changed.pricing_data).toEqual(original.pricing_data);
  expect(changed.status).toBe('sent');
  const edited = normalizeCatalogProposal({ ...original, service_specific_data: { ...original.service_specific_data, catalogJob: { ...job, bedrooms: 5 } } }, original);
  expect(edited.service_specific_data.estimateSnapshot).toEqual(estimateV1({ ...job, bedrooms: 5 }));
});
it('rejects version switching and sample saving', () => {
  const p = composeCatalogProposal({ job: defaultJob(), client });
  expect(() => normalizeCatalogProposal({ ...p, service_specific_data: { ...p.service_specific_data, catalogJob: { ...defaultV1(), access: '' } } }, p)).toThrow('version');
  expect(() => normalizeCatalogProposal(composeCatalogProposal({ job: { ...defaultJob(), demo: true }, client }))).toThrow('Sample');
});
it('warns about below-minimum overrides and long crew days', () => {
  const job = defaultJob('first_deep'); job.squareFeet = 10000;
  job.override = { pricePerVisit: 10, reason: 'Recorded internal rationale' };
  expect(estimateJob(job).warnings.join(' ')).toMatch(/eight hours.*minimum visit charge/);
});
it('malformed historical document blocks degrade without a crash', () => {
  expect(() => catalogDocumentText('```veliz_scope_table\n{oops}\n```')).not.toThrow();
  expect(() => catalogDocumentText('```veliz_pricing_table\nnull\n```')).not.toThrow();
});
it('initial clean has a separate deep-clean price before recurring visits', () => {
  const job = defaultJob();
  const p = composeCatalogProposal({ job, client });
  const initial = estimateJob({ ...job, jobType: 'first_deep', frequency: 'one-time', initialClean: false }).selectedPrice;
  expect(p.generated_content).toContain(`Initial detailed clean: $${initial.toFixed(2)}`);
  expect(initial).toBeGreaterThan(estimateJob(job).selectedPrice);
  expect(p.generated_content).toContain('replaces the first standard visit');
});
it('scope edits are controlled by the saved catalog and cannot forge the quote', () => {
  const job = defaultJob('standard');
  job.scopeOmissions = ['Empty ordinary household trash']; job.scopeAdditions = 'Wipe the breakfast table'; job.coverLetter = 'Thank you for inviting our team.';
  const p = composeCatalogProposal({ job, client });
  expect(p.generated_content).not.toContain('Empty ordinary household trash');
  expect(p.generated_content).toContain('Wipe the breakfast table');
  expect(p.generated_content).toContain('Thank you for inviting our team.');
  expect(p.pricing_data?.price_range?.high).toBe(estimateJob(defaultJob('standard')).selectedPrice);
  expect(() => composeCatalogProposal({ job: { ...job, scopeOmissions: ['Unknown catalog item'] }, client })).toThrow('catalog version');
});

it.each(['recurring_standard', 'airbnb_turnover'] as const)('reopens and edits realistic v1 %s without changing its monetary basis', type => {
  const job = { ...defaultV1(type), operatorNotes: 'Please close the door on exit. Mopping included.' };
  const original = composeCatalogProposal({ job, client });
  expect(catalogAnalytics(original)).toMatchObject({ catalog_version: '2026-09-22.1' });
  expect(estimateJob(job)).toEqual(estimateV1(job));
  const changedJob = { ...job, squareFeet: 1800, companyName: 'Keystone Cleaning' };
  const revised = normalizeCatalogProposal({ ...original, service_specific_data: { ...original.service_specific_data, catalogJob: changedJob } }, original);
  expect(revised.pricing_data?.price_range).toEqual({ low: estimateV1({ ...job, squareFeet: 1800 }).periodPrice, high: estimateV1({ ...job, squareFeet: 1800 }).periodPrice });
  expect(revised.generated_content).toContain('close the door');
  if (type === 'airbnb_turnover') {
    expect(revised.generated_content).not.toMatch(/Expected turns per month|monthly budget|per-turn service agreement/);
    expect(revised.generated_content).toContain('one-time job total');
  }
});
it('v1 validation remains same-day and does not accept v2 pricing drivers', () => {
  const job = defaultV1('airbnb_turnover');
  expect(jobSchema.safeParse({ ...job, turnover: { ...job.turnover, nextDay: true } }).success).toBe(false);
  expect(jobSchema.safeParse({ ...job, levels: 2 }).success).toBe(false);
});
it('persists initial clean separately without adding it to ongoing dashboard value', () => {
  const job = defaultJob();
  const p = composeCatalogProposal({ job, client });
  expect(p.service_specific_data.pricingLineItems).toEqual([
    { kind: 'service', amount: estimateJob(job).selectedPrice, basis: 'per_visit' },
    { kind: 'initial_clean', amount: 310, basis: 'one_time_replaces_first_visit' },
  ]);
  expect(p.service_specific_data.priceBasis).toBe('per_visit');
  expect(catalogDocumentText(p.generated_content!)).toContain('Initial detailed clean (replaces first visit) (Once): **$310.00**');
});

it('JSONB key reordering alone preserves stored proposal bytes and historical prices', () => {
 const original = composeCatalogProposal({ job: { ...defaultV1(), operatorNotes: 'Close the door after mopping.' }, client });
 original.generated_content = 'Accepted historical content';
 original.pricing_data = { price_range: { low: 449.97, high: 449.97 } };
 const reorder = (value: any): any => Array.isArray(value) ? value.map(reorder) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).reverse().map(([key, item]) => [key, reorder(item)])) : value;
 const result = normalizeCatalogProposal({ ...original, status: 'sent', service_specific_data: { ...original.service_specific_data, catalogJob: reorder(original.service_specific_data.catalogJob) }, global_inputs: reorder(original.global_inputs), generated_content: 'Untrusted replacement', pricing_data: { price_range: { low: 1, high: 1 } } }, original);
 expect(result).toEqual({ ...original, status: 'sent' });
});

it('initial clean ignores ongoing labor-hours and price overrides even under heavy condition', () => {
 for (const condition of ['normal', 'heavy'] as const) {
   const base = { ...defaultJob(), condition };
   const overridden = { ...base, costs: { ...base.costs, laborHours: 3 }, override: { pricePerVisit: 150, reason: 'Ongoing service agreement' } };
   const p = composeCatalogProposal({ job: overridden, client });
   const initial = p.service_specific_data.pricingLineItems[1];
   expect(initial.amount).toBe(composeCatalogProposal({ job: base, client }).service_specific_data.pricingLineItems[1].amount);
   expect(initial.amount).toBeGreaterThan(150);
   expect(p.service_specific_data.estimateSnapshot.periodPrice).toBe(325);
 }
});
