import type { Metadata } from "next";
import Link from "next/link";
import CleaningBidCalculator from "@/features/resources/cleaning-bid-calculator";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Free Commercial Cleaning Bid Calculator",
  description: "Estimate monthly labor cost, overhead, profit margin, and a recommended price for a commercial cleaning or janitorial contract.",
  alternates: { canonical: "/tools/cleaning-bid-calculator" },
  openGraph: { title: "Free Commercial Cleaning Bid Calculator", description: "Model a profitable janitorial bid using labor, burden, supplies, overhead, and target margin.", url: `${SITE_URL}/tools/cleaning-bid-calculator`, images: [{ url: `${SITE_URL}/images/og-image.png`, width: 1200, height: 630, alt: "Veltex AI commercial cleaning bid calculator" }] },
  twitter: { card: "summary_large_image", title: "Free Commercial Cleaning Bid Calculator", description: "Model labor, burden, supplies, overhead, and target margin.", images: [`${SITE_URL}/images/og-image.png`] },
};

export default function CalculatorPage() {
  const schema = { "@context": "https://schema.org", "@type": "WebApplication", name: "Commercial Cleaning Bid Calculator", applicationCategory: "BusinessApplication", operatingSystem: "Web", url: `${SITE_URL}/tools/cleaning-bid-calculator`, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };
  return <main className="min-h-screen bg-slate-50 text-slate-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><header className="bg-gradient-to-br from-blue-950 to-blue-700 px-4 py-16 text-white"><div className="mx-auto max-w-6xl"><Link href="/resources" className="text-sm font-semibold text-blue-100">← Free resources</Link><p className="mt-10 text-sm font-bold uppercase tracking-[0.2em] text-emerald-300">Free · No signup required</p><h1 className="mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">Commercial Cleaning Bid Calculator</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-blue-100">Build a bottom-up monthly estimate from labor, payroll burden, supplies, overhead, and target profit margin. Change any input to pressure-test the bid.</p></div></header><section className="mx-auto max-w-6xl px-4 py-12"><CleaningBidCalculator emailCaptureEnabled={process.env.CALCULATOR_EMAIL_CAPTURE_ENABLED === "true"} /><div className="mx-auto mt-16 max-w-3xl"><h2 className="text-3xl font-bold">How the cleaning bid calculation works</h2><p className="mt-4 text-lg leading-8 text-slate-700">The calculator converts weekly visits into an average month using 4.33 weeks, multiplies visits by labor hours, and applies wage plus payroll burden. Supplies and overhead are then added before the target profit margin is calculated.</p><h2 className="mt-10 text-2xl font-bold">Margin is different from markup</h2><p className="mt-4 text-lg leading-8 text-slate-700">The recommended selling price divides estimated cost by one minus the target margin. If monthly cost is $4,000 and the target margin is 20%, the recommended price is $5,000—not $4,800. Use your actual costs and inspect the facility before submitting any quote.</p><p className="mt-8"><Link href="/resources/how-to-bid-commercial-cleaning-jobs" className="font-semibold text-blue-700 hover:underline">Read the complete commercial cleaning bidding guide →</Link></p></div></section></main>;
}
