import { createHash } from "node:crypto";
import type { CampaignBrief, ContentDraft, CreativeUnit, Platform, ReelScript, ResearchInsight } from "./types";
import { auditDraft } from "./policy";

const platformConfig: Record<Platform, { format: ContentDraft["format"]; link: "bio" | "caption" | "first_comment" | "description" }> = {
  facebook: { format: "reel", link: "caption" }, instagram: { format: "reel", link: "bio" },
  linkedin: { format: "native_video", link: "first_comment" }, youtube: { format: "short", link: "description" },
};
const shortHash = (value: string) => createHash("sha256").update(value).digest("hex").slice(0, 20);
function trackedUrl(brief: CampaignBrief, platform: Platform, unit: CreativeUnit): string { const url = new URL(brief.destinationUrl); url.searchParams.set("utm_source", platform); url.searchParams.set("utm_medium", brief.trafficMedium); url.searchParams.set("utm_campaign", brief.id); url.searchParams.set("utm_content", `${unit.seriesId}-${unit.hookVariantId}`); return url.toString(); }

type Series = { id: string; duration: number; length: CreativeUnit["lengthBucket"]; hook: (i: ResearchInsight) => string; visual: string; middle: (i: ResearchInsight) => string; cta: string; thumbnail: string };
const SERIES: Series[] = [
  { id: "bid-teardown", duration: 50, length: "40-60", hook: () => "This cleaning bid looked profitable. One missing line changed the answer.", visual: "Anonymized bid sheet with one cost line highlighted", middle: (i) => `${i.audienceProblem} Walk through the labor, burden, overhead, supplies, and margin assumptions one by one.`, cta: "Pressure-test your own estimate with the free calculator.", thumbnail: "FIND THE BID LEAK" },
  { id: "missing-number", duration: 20, length: "15-22", hook: () => "Your hourly wage is not your complete labor cost.", visual: "Founder writes wage, burden, and true labor cost on a whiteboard", middle: (i) => i.summary, cta: "Check the complete cost before quoting.", thumbnail: "THE NUMBER YOU MISSED" },
  { id: "scope-words", duration: 25, length: "20-30", hook: () => "‘General cleaning’ can become an expensive sentence.", visual: "Proposal wording on screen with vague language crossed out", middle: (i) => `${i.audienceProblem} Define tasks, frequency, options, exclusions, and customer responsibilities.`, cta: "Build a scope your customer and team can understand.", thumbnail: "WORDS THAT COST YOU" },
  { id: "build-with-me", duration: 42, length: "30-45", hook: () => "Let’s turn walkthrough notes into a cleaning proposal.", visual: "Real screen recording of the Veltex AI workflow", middle: () => "Enter the job details, review labor and pricing assumptions, organize the scope, then create the customer-ready proposal.", cta: "Try the calculator, then build your proposal.", thumbnail: "BUILD A BID WITH ME" },
  { id: "walkthrough", duration: 30, length: "20-30", hook: () => "Before you quote this facility, count this.", visual: "Founder on a real facility walkthrough showing one measurable condition", middle: (i) => i.summary, cta: "Capture the condition before you calculate the price.", thumbnail: "CHECK THIS FIRST" },
  { id: "owner-qa", duration: 30, length: "20-30", hook: () => "A cleaning owner asked: how do I know this bid can support the work?", visual: "Founder answers a real, approved audience question on camera", middle: (i) => `${i.summary} Use verified inputs and review the result before sending any quote.`, cta: "Send your next bidding question for a future Q&A.", thumbnail: "OWNER Q&A" },
];

function scriptFor(series: Series, insight: ResearchInsight): ReelScript { return { hook: series.hook(insight), targetSeconds: series.duration, thumbnailText: series.thumbnail, scenes: [
  { seconds: "0-3", visual: series.visual, voiceover: series.hook(insight), onScreenText: series.thumbnail },
  { seconds: `3-${Math.max(10, series.duration - 12)}`, visual: "Pattern interrupts every 2–4 seconds using product UI, facility detail, or annotated numbers", voiceover: series.middle(insight), onScreenText: insight.title },
  { seconds: `${Math.max(10, series.duration - 12)}-${series.duration}`, visual: "Show the relevant Veltex AI screen or free calculator", voiceover: series.cta, onScreenText: series.cta },
], caption: `${insight.summary}\n\nBuilt for commercial cleaning companies that want a clearer path from walkthrough to proposal.`, callToAction: series.cta, shotNotes: ["Vertical 9:16 master", "Readable first-frame text before audio", "Burned-in captions", "Visual change every 2–4 seconds", "Use original product or facility footage", "Use commercially licensed audio only", "Keep key text inside platform-safe areas"] }; }

export function createCreativeUnits(insights: ResearchInsight[], brief: CampaignBrief): CreativeUnit[] { return insights.map((insight, index) => { if (!insight.verified) throw new Error(`Unverified research cannot be drafted: ${insight.id}`); const series = SERIES[index % SERIES.length]; return { id: `${brief.id}-${series.id}-${insight.id}`, campaignId: brief.id, seriesId: series.id, sourceInsightIds: [insight.id], claimIds: insight.claimIds ?? [`claim-${insight.id}`], pillar: series.id === "build-with-me" ? "product_demo" : series.id === "owner-qa" ? "founder_authority" : "education", funnelStage: series.id === "build-with-me" ? "conversion" : "consideration", workingTitle: insight.title, hookVariantId: "a", lengthBucket: series.length, script: scriptFor(series, insight), bRollManifest: [series.visual, "Veltex AI product screen", "Founder or real janitorial environment"], productScreens: series.id === "build-with-me" ? ["job-details", "pricing-review", "proposal-preview"] : ["bid-calculator"] }; }); }

export function createPlacements(unit: CreativeUnit, brief: CampaignBrief, now = new Date()): ContentDraft[] { return (Object.keys(platformConfig) as Platform[]).map((platform) => { const config = platformConfig[platform]; const destinationUrl = trackedUrl(brief, platform, unit); const linkInstruction = config.link === "bio" ? "Use the calculator from the link in our bio." : config.link === "first_comment" ? "Calculator link in the first comment." : config.link === "description" ? "Calculator link in the description." : destinationUrl; const id = `${unit.id}-${platform}`; const title = platform === "youtube" ? `${unit.script.thumbnailText}: Commercial Cleaning Bid Tip` : unit.workingTitle; const body = platform === "linkedin" ? `${unit.script.hook}\n\n${unit.script.caption}\n\n${linkInstruction}` : `${unit.script.caption}\n\n${linkInstruction}`; const draft: ContentDraft = { id, idempotencyKey: shortHash(`${brief.id}|${unit.id}|${platform}|${unit.hookVariantId}`), campaignId: brief.id, creativeUnitId: unit.id, sourceInsightIds: unit.sourceInsightIds, claimIds: unit.claimIds, platform, accountId: null, format: config.format, pillar: unit.pillar, funnelStage: unit.funnelStage, title, body, callToAction: unit.script.callToAction, firstComment: config.link === "first_comment" ? destinationUrl : "", thumbnailText: unit.script.thumbnailText, hashtags: platform === "youtube" ? ["Shorts", "JanitorialBusiness", "CleaningBusiness"] : ["JanitorialBusiness", "CommercialCleaning", "CleaningBids"], destinationUrl, scheduledFor: null, state: "draft", compliance: null, reel: unit.script, createdBy: "100s-content-engine", approvedBy: null, approvedAt: null, reviewerNotes: null, createdAt: now.toISOString() }; return { ...draft, compliance: auditDraft(draft, brief, now) }; }); }
export function repurposeInsight(insight: ResearchInsight, brief: CampaignBrief, now = new Date()): ContentDraft[] { return createPlacements(createCreativeUnits([insight], brief)[0], brief, now); }
export function buildLaunchBank(insights: ResearchInsight[], brief: CampaignBrief, now = new Date()): { units: CreativeUnit[]; placements: ContentDraft[] } { const units = createCreativeUnits(insights, brief); return { units, placements: units.flatMap((unit) => createPlacements(unit, brief, now)) }; }
