import { createHash } from "node:crypto";
import { RULES_VERSION, type CampaignBrief, type ComplianceVerdict, type ContentDraft, type DraftState, type Platform } from "./types";
export const WEEKLY_CAPS: Record<Platform, number> = { facebook: 5, instagram: 5, linkedin: 3, youtube: 3 };
const ALLOWED_UTM_KEYS = new Set(["utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term"]);
const riskRules = [
  { id: "unsupported-guarantee", pattern: /\bguarantee(?:d|s)?\b/i },
  { id: "contract-outcome-promise", pattern: /\b(?:will|always) win\b/i },
  { id: "unsubstantiated-growth", pattern: /\b(?:double|triple|increase) (?:your )?(?:profit|revenue|close rate)\b/i },
  { id: "risk-free-claim", pattern: /\bno risk\b/i },
];
function contentStrings(draft: ContentDraft): string[] { const reel = draft.reel; return [draft.title, draft.body, draft.callToAction, draft.firstComment, draft.thumbnailText, ...(reel ? [reel.hook, reel.caption, reel.callToAction, reel.thumbnailText, ...reel.scenes.flatMap((scene) => [scene.voiceover, scene.onScreenText])] : [])]; }
export function contentHash(draft: ContentDraft): string { return createHash("sha256").update(JSON.stringify({ campaignId: draft.campaignId, creativeUnitId: draft.creativeUnitId, platform: draft.platform, format: draft.format, title: draft.title, body: draft.body, callToAction: draft.callToAction, firstComment: draft.firstComment, thumbnailText: draft.thumbnailText, hashtags: draft.hashtags, destinationUrl: draft.destinationUrl, claimIds: [...draft.claimIds].sort(), reel: draft.reel })).digest("hex"); }
export function isApprovedDestination(destination: string, brief: CampaignBrief): boolean { try { const actual = new URL(destination); const approved = new URL(brief.destinationUrl); const allowedPaths = new Set(brief.approvedDestinationPaths ?? [approved.pathname]); if (actual.protocol !== "https:" || actual.origin !== approved.origin || !allowedPaths.has(actual.pathname)) return false; for (const key of actual.searchParams.keys()) if (!ALLOWED_UTM_KEYS.has(key)) return false; return true; } catch { return false; } }
export function auditDraft(draft: ContentDraft, brief: CampaignBrief, now = new Date()): ComplianceVerdict { const text = contentStrings(draft).join("\n"); const flags: string[] = []; for (const rule of riskRules) if (rule.pattern.test(text)) flags.push(rule.id); for (const claim of brief.prohibitedClaims) if (text.toLowerCase().includes(claim.toLowerCase())) flags.push(`prohibited-claim:${claim}`); if (!isApprovedDestination(draft.destinationUrl, brief)) flags.push("unapproved-destination"); if (!draft.callToAction.trim()) flags.push("missing-call-to-action"); if (["reel", "short", "native_video"].includes(draft.format) && !draft.reel) flags.push("missing-video-script"); if (draft.reel && draft.reel.targetSeconds > 60) flags.push("video-over-60-seconds"); if (!draft.claimIds.length && draft.pillar !== "founder_authority") flags.push("missing-substantiation"); const approvedIds = new Set(brief.approvedClaimIds ?? []); for (const claimId of draft.claimIds) if (!approvedIds.has(claimId)) flags.push(`unapproved-claim:${claimId}`); const uniqueFlags = [...new Set(flags)]; return { rulesVersion: RULES_VERSION, contentHash: contentHash(draft), approved: uniqueFlags.length === 0, flags: uniqueFlags, evaluatedAt: now.toISOString() }; }
const transitions: Record<DraftState, DraftState[]> = { draft: ["needs_review", "rejected"], needs_review: ["approved", "rejected", "draft"], approved: ["scheduled", "draft", "rejected"], scheduled: ["published", "approved"], published: [], rejected: ["draft"] };
export function transitionDraft(draft: ContentDraft, next: DraftState, brief: CampaignBrief, actor: string, notes: string | null = null, now = new Date()): ContentDraft { if (!transitions[draft.state].includes(next)) throw new Error(`Invalid state transition: ${draft.state} -> ${next}`); const compliance = auditDraft(draft, brief, now); if ((next === "approved" || next === "scheduled") && !compliance.approved) throw new Error(`Draft has unresolved risk flags: ${compliance.flags.join(", ")}`); if (next === "scheduled" && !draft.scheduledFor) throw new Error("A scheduled draft requires scheduledFor"); return { ...draft, state: next, compliance, approvedBy: next === "approved" ? actor : draft.approvedBy, approvedAt: next === "approved" ? now.toISOString() : draft.approvedAt, reviewerNotes: notes ?? draft.reviewerNotes }; }
export function assertApprovalIsCurrent(draft: ContentDraft): void { if (!draft.compliance?.approved || draft.compliance.contentHash !== contentHash(draft)) throw new Error("Content changed after compliance review"); if (!draft.approvedBy || !draft.approvedAt) throw new Error("Missing approval evidence"); }
export function assertCadence(drafts: ContentDraft[], existing: ContentDraft[] = []): void { const counts = new Map<string, number>(); for (const draft of [...existing, ...drafts].filter((item) => item.scheduledFor)) { const date = new Date(draft.scheduledFor!); const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "America/New_York", year: "numeric", month: "2-digit", day: "2-digit", weekday: "short" }).formatToParts(date); const fields = Object.fromEntries(parts.map(({ type, value }) => [type, value])); const calendarDay = new Date(`${fields.year}-${fields.month}-${fields.day}T12:00:00Z`); const day = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].indexOf(fields.weekday); calendarDay.setUTCDate(calendarDay.getUTCDate() - ((day + 6) % 7)); const key = `${draft.platform}:${calendarDay.toISOString().slice(0, 10)}`; const count = (counts.get(key) ?? 0) + 1; counts.set(key, count); if (count > WEEKLY_CAPS[draft.platform]) throw new Error(`Weekly cadence exceeded for ${draft.platform}`); } }
